## python libraries

### Numpy

## numpy full form numericals python

## it was founded in 2005
## founder- Travis Oliphant

## it is used for creating array

In [4]:
## create 1D array
import numpy
x=numpy.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
## create 2D Array
import numpy as np
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [7]:
## create 3D Array
import numpy as np
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(z[0])

[1 2 3]


In [10]:
print(z[0,0])

1


In [11]:
print(z[0,2])

3


In [13]:
print(z.ndim)

2


In [14]:
z.ndim

2

In [15]:
x.ndim

1

In [16]:
z.shape


(3, 3)

In [17]:
z.size

9

In [18]:
p=np.array([1,2,3],dtype=complex)
print(p)

[1.+0.j 2.+0.j 3.+0.j]


In [19]:
s=np.array([1,2,3,4,5],ndmin=1)
print(s)

[1 2 3 4 5]


## Array Slicing

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[:5]

array([0, 1, 2, 3, 4])

In [25]:
x[::2]

array([0, 2, 4, 6, 8])

In [26]:
x[0:9:2]

array([0, 2, 4, 6, 8])

In [27]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x[9:4:-2]

array([9, 7, 5])

In [29]:
a2=np.arange(100).reshape(10,10)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
a4=np.arange(12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
s1=np.ones((3,3))
s1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
s2=s1+3
s2


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [34]:
print(np.sin(a2))

[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
  -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
  -0.28790332 -0.96139749 -0.75098725  0.14987721]
 [ 0.91294525  0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175
   0.76255845  0.95637593  0.27090579 -0.66363388]
 [-0.98803162 -0.40403765  0.55142668  0.99991186  0.52908269 -0.42818267
  -0.99177885 -0.64353813  0.29636858  0.96379539]
 [ 0.74511316 -0.15862267 -0.91652155 -0.83177474  0.01770193  0.85090352
   0.90178835  0.12357312 -0.76825466 -0.95375265]
 [-0.26237485  0.67022918  0.98662759  0.39592515 -0.55878905 -0.99975517
  -0.521551    0.43616476  0.99287265  0.63673801]
 [-0.30481062 -0.96611777 -0.7391807   0.1673557   0.92002604  0.82682868
  -0.02655115 -0.85551998 -0.89792768 -0.11478481]
 [ 0.77389068  0.95105465  0.25382336 -0.67677196 -0.98514626 -0.38778164
   0.56610764  0.99952016  0.51397846 -0.44411267]


In [36]:
print(np.cos(a2))

[[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
   0.96017029  0.75390225 -0.14550003 -0.91113026]
 [-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722 -0.75968791
  -0.95765948 -0.27516334  0.66031671  0.98870462]
 [ 0.40808206 -0.54772926 -0.99996083 -0.53283302  0.42417901  0.99120281
   0.64691932 -0.29213881 -0.96260587 -0.74805753]
 [ 0.15425145  0.91474236  0.83422336 -0.01327675 -0.84857027 -0.90369221
  -0.12796369  0.76541405  0.95507364  0.26664293]
 [-0.66693806 -0.98733928 -0.39998531  0.5551133   0.99984331  0.52532199
  -0.43217794 -0.99233547 -0.64014434  0.30059254]
 [ 0.96496603  0.7421542  -0.16299078 -0.91828279 -0.82930983  0.02212676
   0.85322011  0.89986683  0.11918014 -0.77108022]
 [-0.95241298 -0.25810164  0.67350716  0.98589658  0.39185723 -0.56245385
  -0.99964746 -0.5177698   0.44014302  0.99339038]
 [ 0.6333192  -0.30902273 -0.96725059 -0.73619272  0.17171734  0.92175127
   0.82433133 -0.03097503 -0.85780309 -0.89597095]


In [37]:
x=np.random.rand(2,5)
x

array([[0.420586  , 0.82814282, 0.90104156, 0.72150888, 0.29173865],
       [0.64297065, 0.44820081, 0.04659   , 0.56586917, 0.03801299]])

In [39]:
x1=np.random.randint(3,size=10)
x1

array([1, 1, 2, 0, 2, 0, 0, 2, 2, 1])

In [40]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [42]:
print(len(dir(np)))

620


In [44]:
np.__version__

'1.19.2'

## Filtering Arrays

In [49]:
import numpy as np
ary=np.array([11,12,13,14])
x=[True,False,True,False]
nary=ary[x]
print(nary)

[11 13]


In [51]:
import numpy as np
ary=np.array([11,12,13,14])
print(ary)
x=[True,False,True,False]
nary=ary[x]
print(nary)


[11 12 13 14]
[11 13]


In [53]:
ar=np.array([1,2,3,4,5])
filter_ar=ar%2==0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[False  True False  True False]
[2 4]


In [55]:
ar=np.array([1,2,3,4,5])
filter_ar=ar%2!=0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[ True False  True False  True]
[1 3 5]


In [56]:
ar=np.array([1,2,3,4,5])
filter_ar=ar%2==1
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[ True False  True False  True]
[1 3 5]
