## Day_6 Agenda:
     - intro about machine learning
         - For Data analysis
             - numpy
             - pandas
             - matplotlib
             -seaborn
          - Types of machine learning techniques
              - supervised learning
                 - classification
                    - SVM(support vector machine)
                    - Naive Bayes
                    - K Nearest Neighbour
                    - Decesion Tree
                    - Random Forest
                 - regression
                    - Linear Regression
                    - Polynomial(multi varient)
                    - Logistic Regrssion
                    - Decision Tree
              - unsupervised learnimng
                    - Clustering
                       - k means
                        - k median
                        - SOM
                        - Hierarchial       
              - Reinforcement
     
     - Framework -Django
         - develop basic application
         
     - Heroku
        - Deploying our project into server
          - without Db
          - with db(protgres sql)

## T-Shirt Size Prediction


In [7]:
import numpy as np
import pandas as pd

In [8]:
#get the data from source files
data=pd.read_csv('mydata.csv')
print(data)

    Height  weight  size
0      158      58     M
1      158      59     M
2      180     120   XXl
3      158      63     M
4      160      59     M
5      170      80    XL
6      163      60     M
7      192     150  XXXL
8      165      62     L
9      165      63     L
10     168      66     L
11     150      42     S
12     155      48     S
13     142      40     S
14     185      90   XXL
15     170      70    XL
16     192     150  XXXL
17     160      90    XL
18     180      80   XXL


## preprocesssing data
- data.isnull().sum()
- data.fillna(0)
- mean=data['weight].mean
   - print(mean)
   - data.fillna(mean)
   - data.bfill()
   - data.f
- Less Null Values
  - data=data.dropna()
   - print(data) 

In [9]:
data=pd.read_csv('mydata.csv')
print(data)

    Height  weight  size
0      158      58     M
1      158      59     M
2      180     120   XXl
3      158      63     M
4      160      59     M
5      170      80    XL
6      163      60     M
7      192     150  XXXL
8      165      62     L
9      165      63     L
10     168      66     L
11     150      42     S
12     155      48     S
13     142      40     S
14     185      90   XXL
15     170      70    XL
16     192     150  XXXL
17     160      90    XL
18     180      80   XXL


In [11]:
#x=Input values(Features)//independent
#y=Output values(Target)//dependent
x=data[['weight','Height']]
print(x)


    weight  Height
0       58     158
1       59     158
2      120     180
3       63     158
4       59     160
5       80     170
6       60     163
7      150     192
8       62     165
9       63     165
10      66     168
11      42     150
12      48     155
13      40     142
14      90     185
15      70     170
16     150     192
17      90     160
18      80     180


In [12]:
x=data[['weight','Height']]
#print(x)
y=data['size']
print(y)

0        M
1        M
2      XXl
3        M
4        M
5       XL
6        M
7     XXXL
8        L
9        L
10       L
11       S
12       S
13       S
14     XXL
15      XL
16    XXXL
17      XL
18     XXL
Name: size, dtype: object


In [14]:
x=data[['weight','Height']]
#print(x)
y=data['size']
#print(y)
from sklearn.preprocessing import LabelEncoder
y_label=LabelEncoder()
Y=y_label.fit_transform(y)
print(Y)

[1 1 6 1 1 3 1 5 0 0 0 2 2 2 4 3 5 3 4]


In [18]:
## modeling
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.3,random_state=3)
print(x_train,x_test,y_train,y_test)

    weight  Height
6       60     163
7      150     192
14      90     185
11      42     150
9       63     165
18      80     180
17      90     160
13      40     142
5       80     170
0       58     158
8       62     165
3       63     158
10      66     168     weight  Height
12      48     155
2      120     180
1       59     158
16     150     192
4       59     160
15      70     170 [1 5 4 2 0 4 3 2 3 1 0 1 0] [2 6 1 5 1 3]


In [19]:
print(x_test)

    weight  Height
12      48     155
2      120     180
1       59     158
16     150     192
4       59     160
15      70     170


In [20]:
#importing Algorithm and apply to them
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
print(knn.predict(x_test))

[1 3 1 3 1 0]


In [21]:
print(x_test)

    weight  Height
12      48     155
2      120     180
1       59     158
16     150     192
4       59     160
15      70     170


In [22]:
knn.predict([[48,155]])

array([1])

In [23]:
knn.predict([[120,180]])

array([3])

In [24]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,knn.predict(x_test))*100)

33.33333333333333
